#!/bin/bash

notify_user()
{
    # do ntfy magic here
    echo "Sorry, idunno where to send the notification :("
}

if [[ $# -eq 1 ]]; then
    notify_user "$1"
else
    echo "Usage: ntfy [message]"
fi
